/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_aba_include_h__
#define _mulle_aba_include_h__

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-allocator`
// (Use 9DB39403-9DF3-4E29-8871-E8D6023B9334 instead of mulle-allocator, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-allocator no-header`
//    rename              : `mulle-sde dependency|library set mulle-allocator include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-allocator <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-allocator [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-allocator [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-allocator [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-allocator no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-allocator/mulle-allocator.h>   // mulle-allocator

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-thread`
// (Use FDD72DA6-03FE-41C8-AC5E-BDC4E891E0E3 instead of mulle-thread, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-thread no-header`
//    rename              : `mulle-sde dependency|library set mulle-thread include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-thread <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-thread [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-thread [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-thread [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-thread no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-thread/mulle-thread.h>   // mulle-thread

// To remove the following dependency (headers and library) completely:
//   `mulle-sde dependency remove mulle-linkedlist`
// (Use 7ACE8853-C4E5-499A-951D-A9CDCC85785F instead of mulle-linkedlist, if there are duplicate entries)
//
// You can tweak the following #include with these commands:
//    remove #include: `mulle-sde dependency mark mulle-linkedlist no-header`
//    rename              : `mulle-sde dependency|library set mulle-linkedlist include whatever.h`
//    reorder             : `mulle-sde dependency move mulle-linkedlist <up|down>`
//    toggle #include: `mulle-sde dependency mark mulle-linkedlist [no-]import`
//    toggle public       : `mulle-sde dependency mark mulle-linkedlist [no-]public`
//    toggle optional     : `mulle-sde dependency mark mulle-linkedlist [no-]require`
//    remove for platform : `mulle-sde dependency mark mulle-linkedlist no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-linkedlist/mulle-linkedlist.h>   // mulle-linkedlist

#endif
